name: Release Library

on:
  repository_dispatch:
    types:
      - release_library

jobs:
  build:
    name: Create Library Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Prepare Data
        id: data
        run: |
          echo ::set-output name=type::$(echo ${{ github.event.client_payload.ref }} | cut -d"/" -f2)
          echo ::set-output name=tag::$(echo ${{ github.event.client_payload.ref }} | cut -d"/" -f3)
      - name: Tag latest commit
        id: tag_release
        if: steps.data.outputs.type == 'tags'
        run: |
          git config --global user.email "info@typo3.com"
          git config --global user.name "GitHub Actions"
          git tag -a ${{ steps.data.outputs.tag }} -m "[RELEASE] ${{ steps.data.outputs.tag }}"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release notes
        if: steps.data.outputs.type == 'tags'
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: ${{ steps.data.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
